### ISSUE TITLE
'Config' object has no attribute 'APPLE_LOOCV_ALL_WINDOWED'

### ISSUE THREAD

**Issue by bf-yang** [bzhai/Ubi-SleepNet#1]
When use apple dataset, and use "train_val_test". It report 'Config' object has no attribute 'APPLE_LOOCV_ALL_WINDOWED'

**Comment by bf-yang** [comment]
Thank you. I downloaded the raw data 'apple_loocv_windowed_50.h5' and saved it in Dataset file. But it reports: "[Errno 2] File b'Dataset/Apple_watch_sleep_dataset/outputs/features/apple_16_fold.csv' does not exist: b'Dataset/Apple_watch_sleep_dataset/outputs/features/apple_16_fold.csv'"

**Comment by bzhai** [comment]
I also updated the APPLE_LOOCV_PID_PATH file path, it was located under the assets folder
