### ISSUE TITLE
how to build h5 file for apple watch datasets?

### ISSUE THREAD

**Issue by somewayin** [bzhai/Ubi-SleepNet#2]
Can you illustrate the steps to build, thanks！

**Comment by bzhai** [comment]
Sure, I will update the Apple Watch dataset building process in detail.

**Comment by somewayin** [comment]
Thanks!

**Comment by bzhai** [comment]
I have updated the readme.md file. If you build the dataset for the first time, please consider using Pycharm to open the project from the child folder "applewatch_dataprocessing" so the ``import`` commands will not break up.  There is a readme.md file in that folder dedicated to the dataset building.  Please let me know if you have more questions.
