### ISSUE TITLE
h5 files building require statistics files which are not present

### ISSUE THREAD

**Issue by pradical** [bzhai/Ubi-SleepNet#4]
Hi. I am trying to build the Apple Watch dataset that can be fed into the DNNs. I guess the path to create the dataset (is this correct?) is to: 

- Run the preprocessing_runner.py at (https://github.com/bzhai/Ubi-SleepNet/tree/main/applewatch_dataprocessing/source/preprocessing/preprocessing_runner.py). 
- Then use the h5 dataset builder (Ubi-SleepNet/data_loader/apple_watch_h5_dataset_builder.py) to build the h5 files.
- Then build windowed data which can be used in the models (Ubi-SleepNet/data_loader/apple_sliding_window_dataset_builder.py). 

However, I am running into issues after the first step (preprocessing). It seems the h5 dataset builder expects the input hr_features, act_features and sleep_stages (probably, the output files in features such as "3509524_hr_feature.out") to have a total number of columns of 9: ["activity", "min_hr", "max_hr", "mean_hr", "skw_hr", "kurt_hr", "std_hr", "linetime", "stages"]. See the attached image, or line 47 of this file: Ubi-SleepNet/data_loader/apple_watch_h5_dataset_builder.py

The output files "*_hr_feature.out" have only one column. In other words, I am not able to understand how the min, max, mean and other statistics are obtained. Can you please tell me how these files are created in the dataset? And how I can go from the Apple Watch dataset to the input features for the Neural Networks?

Appreciate any input. Thanks!

<img width="715" alt="image" src="https://github.com/bzhai/Ubi-SleepNet/assets/18308475/0a7dcbe8-ac84-42ab-b87c-4ba838ee84d2">

**Comment by bzhai** [comment]
Hi, 
The Apple watch dataset requires a preprocessing to be completed. If you are interested, you can use the code from: https://github.com/bzhai/Ubi-SleepNet/tree/main/applewatch_dataprocessing
to process the data. However, I have provided the pre-processed H5 dataset for the replication purpose: https://drive.google.com/drive/folders/1GDPVpUZMes8FZz1fieGQt0eYBEiakUke?usp=sharing

Please let me know if this works for you.

**Comment by pradical** [comment]
Hi,

Thanks very much for the reply, and the data. Feels like I am missing something though, when trying to process the data. 

I am using the code in https://github.com/bzhai/Ubi-SleepNet/tree/main/applewatch_dataprocessing. As I understand, I have to run the preprocessing_runner.py in order to process the data. It produces the `<subject_id>_hr_feature.out` files for Heart Rate. It is a file that contains a 1d array with the smoothened HR features. However it seems the code for the next step,  `apple_watch_h5_dataset_builder.py`, expects a 9 dimensional array in the `<subject_id>_hr_feature.out` file. The 9d array should contain  ["activity", "min_hr", "max_hr", "mean_hr", "skw_hr", "kurt_hr", "std_hr", "linetime", "stages"].

Created this image to summarize my question:

<img width="688" alt="image" src="https://github.com/bzhai/Ubi-SleepNet/assets/18308475/d1531aa3-a314-4d94-b762-e519cab9619d">

Could you tell me how this was created? 

Thanks for the input!

**Comment by bzhai** [comment]
Hi, sorry for the late reply. I was away. I've updated the ```applewatch_dataprocessing``` package with the missing code. If you pull the latest updates and run ```preprocessing_runner.py```, you should see that the *hr.out file contains data with 9 columns."
